# Generated by Django 5.1.3 on 2025-06-17 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0001_initial'),
        ('Unite', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personnel',
            new_name='Profile',
        ),
    ]
