# Generated by Django 5.1.3 on 2025-06-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cin',
            field=models.IntegerField(unique=True),
        ),
    ]
