# Generated by Django 5.1.3 on 2025-06-16 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('codeABarre', models.IntegerField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('numeroSerie', models.IntegerField(max_length=50, unique=True)),
                ('modele', models.CharField(max_length=50)),
                ('marque', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('etat', models.CharField(max_length=50)),
                ('dateMiseEnService', models.DateField()),
                ('adresseIP', models.CharField(max_length=15, unique=True)),
                ('adresseMAC', models.CharField(max_length=17, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('matricule', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('cin', models.IntegerField(max_length=8, unique=True)),
                ('fonction', models.CharField(max_length=50)),
                ('dateNaissance', models.DateField()),
                ('region', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('codePostal', models.IntegerField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('classe', models.CharField(max_length=50)),
                ('gouvernorat', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=200)),
                ('nombreEmployes', models.IntegerField()),
                ('nombreGuichets', models.IntegerField()),
                ('chefUnité', models.CharField(max_length=100)),
                ('plageIP', models.CharField(max_length=100, unique=True)),
                ('typeLiason1', models.CharField(max_length=50)),
                ('typeLiason2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('idTicket', models.AutoField(primary_key=True, serialize=False)),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('dateResolution', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('etat', models.CharField(max_length=50)),
                ('priorite', models.CharField(max_length=50)),
                ('equipement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parc_info.equipement')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parc_info.personnel')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parc_info.unite')),
            ],
        ),
        migrations.AddField(
            model_name='personnel',
            name='unite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parc_info.unite'),
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('idMaintenance', models.AutoField(primary_key=True, serialize=False)),
                ('datecréation', models.DateTimeField()),
                ('bureauSource', models.CharField(max_length=100)),
                ('diagnostique', models.TextField()),
                ('marque', models.CharField(max_length=50)),
                ('typeMaintenance', models.CharField(max_length=50)),
                ('codeEquipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parc_info.equipement')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parc_info.unite')),
            ],
        ),
        migrations.AddField(
            model_name='equipement',
            name='unite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parc_info.unite'),
        ),
    ]
