# Generated by Django 5.1.3 on 2025-06-17 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parc_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='codeEquipement',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='equipement',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='unite',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='unite',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='personnel',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='unite',
        ),
        migrations.DeleteModel(
            name='Equipement',
        ),
        migrations.DeleteModel(
            name='Maintenance',
        ),
        migrations.DeleteModel(
            name='Personnel',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='Unite',
        ),
    ]
