# Generated by Django 5.1.3 on 2025-06-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Unite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unite',
            name='idLiaison1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unite',
            name='idLiaison2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unite',
            name='codePostal',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
