# Generated by Django 5.1.3 on 2025-07-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Unite', '0002_unite_idliaison1_unite_idliaison2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unite',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
