# Generated by Django 5.1.3 on 2025-06-17 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Equipements', '0001_initial'),
        ('Unite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('idMaintenance', models.AutoField(primary_key=True, serialize=False)),
                ('datecréation', models.DateTimeField()),
                ('bureauSource', models.CharField(max_length=100)),
                ('diagnostique', models.TextField()),
                ('marque', models.CharField(max_length=50)),
                ('typeMaintenance', models.CharField(max_length=50)),
                ('codeEquipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipements.equipement')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Unite.unite')),
            ],
        ),
    ]
