# Generated by Django 5.1.3 on 2025-07-01 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maintenance', '0001_initial'),
        ('Ticket', '0004_alter_ticket_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Ticket.ticket'),
            preserve_default=False,
        ),
    ]
