# Generated by Django 5.1.3 on 2025-06-17 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Equipements', '0001_initial'),
        ('Unite', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('idTicket', models.AutoField(primary_key=True, serialize=False)),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('dateResolution', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('etat', models.CharField(max_length=50)),
                ('priorite', models.CharField(max_length=50)),
                ('equipement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Equipements.equipement')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.personnel')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Unite.unite')),
            ],
        ),
    ]
