# Generated by Django 5.1.3 on 2025-06-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='etat',
            field=models.CharField(choices=[('ouvert', 'Ouvert'), ('encours', 'En cours'), ('ferme', 'Fermé')], default='ferme', max_length=50),
        ),
    ]
