# Generated by Django 5.1.3 on 2025-07-01 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0003_alter_ticket_personnel'),
        ('Users', '0005_alter_profile_datenaissance_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.profile'),
        ),
    ]
